### ISSUE TITLE
Bug: weird, unwanted size changes when adding rows or columns during atlas creation

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#142]
When clicking either on + or - to add an extra row or column to the future atlas, the FP size changes inexplicably:
1. If you were close like this:
![selection_013](https://cloud.githubusercontent.com/assets/1291055/8068997/1564d0f6-0ee7-11e5-9845-86debb301ac9.png)
it becomes smaller like that:
![selection_014](https://cloud.githubusercontent.com/assets/1291055/8069012/23d66cee-0ee7-11e5-8297-26dfdb72170b.png)

2. if the FP unit was over a larger area, like this:
![selection_016](https://cloud.githubusercontent.com/assets/1291055/8069030/3f607bc6-0ee7-11e5-9c17-7ef7ab1fe8a8.png)
it becomes really bigger like that:
![selection_017](https://cloud.githubusercontent.com/assets/1291055/8069038/4a3d4c9a-0ee7-11e5-8224-215ae2370b62.png)

Therefore you have to resize again and again your FP. It is the first time I face this, was not the case with v1

**Comment by mojodna** [comment]
Hey, @sconnelley, can you have a look at this?

**Comment by danstowell** [comment]
I just had this too - rather annoying I'm afraid :(

**Comment by almccon** [comment]
Got another report: https://twitter.com/eleanortutt/status/628696578845483008

**Comment by danbjoseph** [comment]
:+1: to this being an issue

<img width="300" alt="screen shot 2015-08-16 at 4 57 05 pm" src="https://cloud.githubusercontent.com/assets/4806884/9293875/41826f5c-443b-11e5-949f-aaf906e6905f.png">
then after adding a column...  
<img width="300" alt="screen shot 2015-08-16 at 4 57 16 pm" src="https://cloud.githubusercontent.com/assets/4806884/9293912/450f605c-443c-11e5-9259-9a37b2b33d2c.png">

**Comment by smarshy** [comment]
Hi! I found a way to fix this issue.But it doesn't take care of the paper aspect ratios.Is it necessary to conserve paper aspect ratio when clicking on '+' and '-'?

**Comment by ian-ross** [comment]
@smarshy  I'm wondering if you just commented out the call to `_updateToolDimensions` in `_updatePages`, which was the first thing I tried...  That suppresses the bug as described, but it does mean that the individual page aspect ratios aren't fixed, which is not acceptable (the aspect raio is fixed by the paper size the user selects, so must be respected in order to be able to produce reasonable-looking atlas pages).  I think we need to think a little bit about how the interaction is expected to work here.  The way I think of it is something like this:

1. The user will select the paper size and aspect ratio they want to use.  This is likely to remain fixed throughout the rest of the interaction.
2. The user selects a region of interest on the map by scrolling and zooming the map and moving and resizing the atlas extents box.
3. The user adds or removes pages to the atlas by clicking the +/- buttons on the atlas composer.
4. The user may then adjust either the atlas extent (by moving or resizing the box) or the number of pages (using the +/- buttons for either rows or columns).

So, questions that naturally arise are:

 * Does the extent of the box change when you click the +/- buttons?  At the moment, this is the case, but I don't know if that's really the best behaviour.  I've seen comments from users (that make sense to me) that it seems more natural to select a region of interest, then have that ROI remain fixed as you select the number of atlas pages used to cover the region.
 * What happens if you resize the box with multiple pages in it?  At the moment, the box resizes maintaining its aspect ratio and the aspect ratios of all its pages.  This seems to me to be the correct behaviour here.

The second point seems like it's already covered correctly by the existing code, but the first point is more complicated.  If you set an ROI (which because of the way the box resizing handle works will have the correct aspect ratio for the selected paper size) and then click the "add column" button, one of three things could happen:

1. The existing behaviour, which is to add a new column with the same size as the existing ROI, thus doubling the area of the ROI.  This has two problems: first, it makes it hard to set up your ROI without a lot of panning and zooming; second, adding the new column can move the UI interaction elements outside of the map viewport, meaning that the user has to pan and/or zoom after adding columns to locate the +/- button again.
2. Split the ROI into two columns, thus breaking the aspect ratio.  Not acceptable behaviour.
3. Split the ROI into two columns, then adjust the number of rows in the ROI to maintain the aspect ratio of the individual pages, i.e. starting from a single page and pressing "add column", you would end up with a 2 rows of 2 columns.  This has the advantage of keeping the ROI fixed, of not unnecessarily moving the UI interaction elements around (so the user can add multiple columns by clicking several times in the same place), and of respecting the paper aspect ratio set by the user.

The obvious objection to option 3 is that as it stands, it's only then possible to make N x N sized atlases, since there's no way of adding a new row or column that extends the ROI.

I don't know the best way of managing the interaction behaviour here.  Any ideas?

**Comment by smarshy** [comment]
@ian-ross No, I did not comment out call to _updateToolDimensions in my final code.I actually did it initially (It was the first thing I tried too) and had this bug fixed.It produced behaviour as suggested  in issue #146 .In this situation, the size of the tool remain fixed while the number of rows and columns changed.This did save a lot of resizing and was sensible but true,individual page aspect ratios aren't fixed.

I have taken a different approach and modified how the dimensions get reassigned in _updateToolDimensions function.While reassigning,I have considered the current size of the tool ,added/subtracted a column/row size and assigned the value to a dimension accordingly and resized the other dimension as per paper aspect ratio.So in this case,you do not get this bug even after zooming in.And the overall paper aspect ratio is conserved.

However, individual pages do not respect these ratios.I just checked.I 'll have to work a bit on that again.

**Comment by ian-ross** [comment]
@smarshy  Sounds like good progress!  I think fixing this particular bug one way or another is one step to fixing issue #146 as well, which will mean working out a good interaction model that satisfies the two constraints of a). having all pages within an atlas have the correct aspect ratio for the selected paper size, and b). allowing the user to create atlases with arbitrary numbers of rows and columns

**Comment by smarshy** [comment]
@ian-ross I think I made a mistake before.I was trying to make the atlas respect  aspect ratios rather than the pages.This is what I now have:

![screenshot from 2015-10-04 16 54 12](https://cloud.githubusercontent.com/assets/13931206/10267965/ebaaddf0-6ac6-11e5-854c-c754c7f4c060.png)

After adding a column:

![screenshot from 2015-10-04 16 54 12](https://cloud.githubusercontent.com/assets/13931206/10267970/008138d2-6ac7-11e5-814f-fa3170da3a14.png)

Then,adding a row:

![screenshot from 2015-10-04 16 54 22](https://cloud.githubusercontent.com/assets/13931206/10267977/11af06d4-6ac7-11e5-9957-581967404638.png)

The tool does not explode and individual aspect ratios are conserved.What do you think?

**Comment by smarshy** [comment]
@ian-ross I think I made a mistake earlier.I was trying to make the atlas obey aspect ratios rather than pages.This is what I finally have:

Initial:
![screenshot from 2015-10-04 165334](https://cloud.githubusercontent.com/assets/13931206/10268067/bfee9770-6aca-11e5-8eb5-661273760588.png)

After adding a column:
![screenshot from 2015-10-04 165412](https://cloud.githubusercontent.com/assets/13931206/10268072/ced2e5ac-6aca-11e5-9c41-f084ad9c9d03.png)

Then,adding a row:
![screenshot from 2015-10-04 165422](https://cloud.githubusercontent.com/assets/13931206/10268076/da2ee630-6aca-11e5-950c-1d8194d4c656.png)

The tool does not explode and individual pages obey aspect ratios.What do you think?

**Comment by ian-ross** [comment]
@smarshy  Looks pretty good!  Do you want to check it into a branch in your fork of the repo so I can pull it and have a look?

**Comment by smarshy** [comment]
@ian-ross yes,I 'll try doing that and then get back to you

**Comment by mojodna** [comment]
@linzjax's PR (https://github.com/fieldpapers/fp-web/pull/15) was just deployed.

@severinmenard @dalekunce mind taking a look at the new behavior to see if it addresses your primary objections?

@linzjax is continuing work on this. More here: https://github.com/Cadasta/fieldpapers/wiki/Outreachy:-Research-for-UI-Redesign

**Comment by ian-ross** [comment]
This should be definitively fixed by https://github.com/fieldpapers/fp-web/pull/23

**Comment by ian-ross** [comment]
This issue should be fixed or rendered obsolete by https://github.com/fieldpapers/fp-web/pull/23: if anyone thinks it's still a problem, please reopen this issue!
