### ISSUE TITLE
Searching existing atlas (including personal ones)

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#143]
Is there a way to find:
    personal atlas (meaning the ones created through the personal account)?
    atlas of other people (location or username)?

**Comment by mojodna** [comment]
Kind of.  Here's the list of atlases that I've created while being logged in:

http://fieldpapers.org/atlases?user=8182

Note that it requires a user id rather than a username.  I was going to create a link for you, but I don't know your username.

I'm tracking that (filtering by username instead of id) as #144.

Locations have worked in the past, although not consistently (not all objects that contain location properties actually have them filled out).  This is #83.
