### ISSUE TITLE
PDF output: QR could not be duplicated and font-size could be bigger (or configurable)

### ISSUE THREAD

**Issue by hllorens** [fieldpapers/fieldpapers#193]
I used field-papers for the first time and found it very intuitive and perfect for my goal (printing a multi-page map).

However there are two things that I felt could be improved:
1) QR illustration was added in the bottom-right corner of every single page of the generated multi-page map. Sadly it randomly covers part of the map which is what the user is interested into (if it is to be printed). I would either only add the QR in one of the pages (probably the first one that contains an index of the multi-page map) or even make it optional for the user if he wants the QR to be printed at all.

2) The font size in town names is rather small. I would make it bigger or let the user select the size. What would be really great is even place an option that makes it bigger based on the town inhabitants amount... but in any case, the configuration option would be the best to satisfy more users.

Thanks for such a great tool!

**Comment by mojodna** [comment]
#101 is (one of) the past comments about the QR code. You're totally right, and we'd like to find a way to improve the atlas layout to help that out.

Since FP currently uses external map layers for the PDFs, it's entirely dependent on how those are styled for font size, color, etc. The long-term roadmap includes one or more map styles specifically designed for integration with Field Papers, but I have no idea when we'll be able to get to that.

One option (specifically for you, but it could be more generally useful) would be to create a new map using Mapbox Studio Classic and boost up the font sizes. You'd then be able to use the URL template for it (the thing with {z}/{x}/{y}) and use that as the source for a new atlas.

**Comment by hllorens** [comment]
For the font-size issue, I have created https://a.tiles.mapbox.com/v4/hllorens.o49co904/page.html?access_token=pk.eyJ1IjoiaGxsb3JlbnMiLCJhIjoiY2lncnc3ejVqMDIxY3N4a25xcXpnaDF5ZCJ9.admNNBeykH1KtdCn0LSsXw#10/38.3163/-0.9023

However I am not sure how to make it show ALL towns at any zoom level. Any hint on that?

**Comment by mojodna** [comment]
@hllorens very nice!

You may be limited by the underlying data in Mapbox Streets, though there may also be something in the style that's limiting it. What are your styles related to the `#place_label` layer?

**Comment by hllorens** [comment]
hi @mojodna 

I finally discovered that what I wanted to add where no towns but villages. Problem solved.

Thanks a lot!

**Comment by mojodna** [comment]
Great! Closing since the QR codes are tracked in #101.
