### ISSUE TITLE
Deploy fp-web

### ISSUE THREAD

**Issue by mojodna** [fieldpapers/fieldpapers#197]
Necessary changes when deploying:

* [x] configure Amazon SES
* [x] set `URL_HOST`
* [x] set `MAIL_SOURCE_ARN`
* [x] set `RDS_*`
* [x] set `MAIL_ORIGIN`

After deploying:

* [x] remove `SMTP_URL`
* [x] remove `DATABASE_URL`

**Comment by mojodna** [comment]
@ian-ross I'm a bit confused by SES, probably by the terminology. I've verified an email address (and have started the process of verifying DKIM) and now have an "Identity ARN". Is that the same as the "mail source ARN"?

Do I also need to attach an SES-related policy (per https://github.com/fieldpapers/fieldpapers/blob/master/aws-quick-start/aws-quick-start.py#L514-L515) to the IAM user that Heroku is using? (We have fp-web deployed using Heroku, so IAM roles are out of the equation.)

What should that look like?  Does this look right?

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Stmt1450144787000",
            "Effect": "Allow",
            "Action": [
                "ses:SendEmail",
                "ses:SendRawEmail"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}
```

**Comment by ian-ross** [comment]
@mojodna  You aren't the only one who's confused by SES!  It took me a long time to get it to work.  The security requirements for SES seem to be tougher than for any other AWS service (presumably because of past problems with spammers?).

The "mail source ARN" is an ARN identifying an originating email address or domain, so it looks like "arn:aws:ses:<region>:<userid>:identity/<mail_origin>" where <mail_origin> is either a single email address or a domain name.  I don't know how that corresponds to the idea of an "identity ARN".  I think the idea here is that you can really lock down who is allowed to send email via SES from AWS accounts you control: as well as saying whether or not they can send email at all, you can associate rules between users and specific email addresses.

That does mean that you do indeed need to attach a sending policy to the IAM user.  The second example on this page shows you what you probably want: http://docs.aws.amazon.com/ses/latest/DeveloperGuide/sending-authorization-policy-examples.html -- it grants blanket sending authorisation for specified IAM users for a specified mail origin (which can be a single address or a domain).

It took me *ages* to work this out the first time.  It's pretty logical once you've seen how it's supposed to work, but the documentation is a bit scattered.

**Comment by mojodna** [comment]
The policy wizard doesn't let me add principals until I get the chance to edit the raw version, so I'm wondering if attaching it as an inline policy to an IAM user achieves the same thing. Hopefully the docs will clarify.

Thanks for paving the path!
