### ISSUE TITLE
aws-quick-start.py error

### ISSUE THREAD

**Issue by mjfoster83** [fieldpapers/fieldpapers#209]
Hi there, running the AWS install script to get a version of this running for a new upcoming project. Script almost finished but get errors when starting EC2. Digging into the error, in my cluster tasks, there are a few stopped tasks that read:

CannotPullContainerError: Error: image fieldpapers/fp-tasks:latest not found

Script still finishes, but unable to load page.

![screen shot 2016-02-03 at 5 34 27 pm](https://cloud.githubusercontent.com/assets/3975334/12799976/01b88cda-caa0-11e5-8219-bcd31a9a59b5.png)

Been banging head for a while and adjusting things, but unsure how to fix. Is this a known error with the script? Are there any workarounds?

Thanks!

**Comment by mojodna** [comment]
@ian-ross knows more about the AWS quick start.

In the meantime, the container should probably be `quay.io/fieldpapers/tasks:v0.9.0`.

**Comment by ian-ross** [comment]
@mjfoster83  The Docker repository that's used for pulling containers is controlled by an environment variable called `FP_DOCKER_REPO` (https://github.com/fieldpapers/fieldpapers/blob/master/aws-quick-start/helpers.py#L287).  I usually build containers of my own and push them to a `cadasta` account on Docker Hub, so I just set `FP_DOCKER_REPO=cadasta` and I'm good.

I hadn't yet thought too hard about anyone else using this, so thanks for volunteering as s guinea pig!

What I think I should do here is to modify the script that sets up the Elastic Beanstalk Docker configuration so that if you don't select a specific `FP_DOCKER_REPO`, it uses a set of default containers.  That's an easy change to make.

@mojodna Can you confirm exactly what should be the default containers to use for `fp-tasks`, `fp-web` and `fp-tiler`?  Then I can set up some defaults so that running this without any extra configuration gives a "vanilla" Field Papers.

**Comment by mjfoster83** [comment]
Hey guys, thanks so much, happy to be a guinea pig. Love the project. The script runs great until it has to run the EC2 start tasks from fp-tasks, fp-web, and fp-tiler. I'm going to dig deeper later today and try some mods on my own fork as I'm gaining more familiarity with the project, but I think using setting it to use the default containers makes a ton of sense.

**Comment by ian-ross** [comment]
Fixing this should only take me five minutes once I know what containers to use.  I could even go and look what's nominally being used now, but I'd rather hear from @mojodna what the exact current versions are.

**Comment by mjfoster83** [comment]
@mojodna @ian-ross super awesome, thanks! let me know when you make that fix

**Comment by mojodna** [comment]
@mjfoster83 https://quay.io/organization/fieldpapers has the latest containers that fieldpapers.org is running. fp-web and fp-tiler both run on Heroku. (Both from `master`.)

Seems like it might make sense to publish the remaining containers to Quay... I thought fp-tiler had one, but apparently not.

**Comment by ian-ross** [comment]
I think that was why I ended up using my own containers.  @mjfoster I can't at the moment suggest setting `FP_DOCKER_REPO=cadasta` because the `fp-web` container on there at the moment is an experimental one that we have out for community testing.  If we don't have a better solution by tomorrow, I'll set up a separate Docker Hub account and will upload good containers there and let you know how to use it.

**Comment by ian-ross** [comment]
@mojodna I've been having a bear of a time trying to get this to work.  I've been trying to make some Docker containers I can put up for @mjfoster83 to use temporarily, but I'm having a total fail.  First, there's a problem with `fp-tasks`.  I'll paste the whole transcript from `docker build` in below, but it seems to be something to do with not being able to find Ubuntu updates.  I see that you changed the Dockerfile here recently, but I can't figure out quite what broke.  But anyway, `fp-tasks` and `fp-tiler` have containers up on `quay.io`, so I can use those.

Now I'm trying to get `fp-web` to work, and I'm not getting anywhere.  It's really confusing, because I did this with no problem at all for the community demo site the other day!  I've spent too much time on this today, so I'll come back to it next week.

@mjfoster83: If you just want something to play with temporarily while we sort this out, you could try cloning the Cadasta/fieldpapers repo and doing `export FP_DOCKER_REPO=cadasta` in your shell before running the `aws-quick-start.py` script.  This won't give you the current Field Papers setup, and there will be cruft to do with surveys and new UI mocks, but you'll be able to play with it.  I just tested it, and it works OK.  Certainly better than anything else I've tried today!

More next week...

fp-tasks transcript:

```
[seneca:fp-tasks] $ docker build -t skybluetrades/fp-tasks .
Sending build context to Docker daemon 48.13 kB
Step 1 : FROM quay.io/fieldpapers/paper:v0.5.0
 ---> c7956d8410a0
Step 2 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 8c8b39851805
Step 3 : RUN apt-get update &&   apt-get upgrade -y &&   apt-get clean
 ---> Using cache
 ---> f65bf6e4893c
Step 4 : RUN apt-get install -y software-properties-common apt-transport-https curl lsb-release &&   add-apt-repository "deb https://deb.nodesource.com/node_5.x $(lsb_release -c -s) main" &&   (curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -) &&   apt-get update &&   apt-get install -y nodejs &&   apt-get clean
 ---> Running in f8b826532c46
Reading package lists...
Building dependency tree...
Reading state information...
lsb-release is already the newest version.
The following extra packages will be installed:
  gir1.2-glib-2.0 iso-codes libcurl3 libdbus-glib-1-2 libgirepository-1.0-1
  python-apt-common python3-apt python3-dbus python3-gi python3-pycurl
  python3-software-properties unattended-upgrades
Suggested packages:
  isoquery python3-apt-dbg python-apt-doc python-dbus-doc python3-dbus-dbg
  libcurl4-gnutls-dev python3-pycurl-dbg bsd-mailx mail-transport-agent
The following NEW packages will be installed:
  apt-transport-https curl gir1.2-glib-2.0 iso-codes libcurl3 libdbus-glib-1-2
  libgirepository-1.0-1 python-apt-common python3-apt python3-dbus python3-gi
  python3-pycurl python3-software-properties software-properties-common
  unattended-upgrades
0 upgraded, 15 newly installed, 0 to remove and 1 not upgraded.
Need to get 3171 kB of archives.
After this operation, 20.6 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/main libdbus-glib-1-2 amd64 0.100.2-1 [74.1 kB]
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main apt-transport-https amd64 1.0.1ubuntu2.10
  404  Not Found [IP: 91.189.92.200 80]
Get:2 http://archive.ubuntu.com/ubuntu/ trusty-updates/main libgirepository-1.0-1 amd64 1.40.0-1ubuntu0.2 [85.6 kB]
Get:3 http://archive.ubuntu.com/ubuntu/ trusty-updates/main gir1.2-glib-2.0 amd64 1.40.0-1ubuntu0.2 [124 kB]
Get:4 http://archive.ubuntu.com/ubuntu/ trusty/main iso-codes all 3.52-1 [2073 kB]
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main python-apt-common all 0.9.3.5ubuntu1
  404  Not Found [IP: 91.189.92.201 80]
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-apt amd64 0.9.3.5ubuntu1
  404  Not Found [IP: 91.189.92.201 80]
Get:5 http://archive.ubuntu.com/ubuntu/ trusty/main python3-dbus amd64 1.2.0-2build2 [82.1 kB]
Get:6 http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-gi amd64 3.12.0-1ubuntu1 [154 kB]
Get:7 http://archive.ubuntu.com/ubuntu/ trusty/main python3-pycurl amd64 7.19.3-0ubuntu3 [47.5 kB]
Get:8 http://archive.ubuntu.com/ubuntu/ trusty-updates/main unattended-upgrades all 0.82.1ubuntu2.3 [25.5 kB]
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main python3-software-properties all 0.92.37.5
  404  Not Found [IP: 91.189.92.201 80]
Err http://archive.ubuntu.com/ubuntu/ trusty-updates/main software-properties-common all 0.92.37.5
  404  Not Found [IP: 91.189.92.201 80]
Err http://archive.ubuntu.com/ubuntu/ trusty-security/main libcurl3 amd64 7.35.0-1ubuntu2.5
  404  Not Found [IP: 91.189.92.201 80]
Err http://archive.ubuntu.com/ubuntu/ trusty-security/main curl amd64 7.35.0-1ubuntu2.5
  404  Not Found [IP: 91.189.92.201 80]
Fetched 2665 kB in 19s (140 kB/s)
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/curl/libcurl3_7.35.0-1ubuntu2.5_amd64.deb  404  Not Found [IP: 91.189.92.201 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/a/apt/apt-transport-https_1.0.1ubuntu2.10_amd64.deb  404  Not Found [IP: 91.189.92.200 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python-apt-common_0.9.3.5ubuntu1_all.deb  404  Not Found [IP: 91.189.92.201 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/p/python-apt/python3-apt_0.9.3.5ubuntu1_amd64.deb  404  Not Found [IP: 91.189.92.201 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/c/curl/curl_7.35.0-1ubuntu2.5_amd64.deb  404  Not Found [IP: 91.189.92.201 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/software-properties/python3-software-properties_0.92.37.5_all.deb  404  Not Found [IP: 91.189.92.201 80]

E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/s/software-properties/software-properties-common_0.92.37.5_all.deb  404  Not Found [IP: 91.189.92.201 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
The command '/bin/sh -c apt-get install -y software-properties-common apt-transport-https curl lsb-release &&   add-apt-repository "deb https://deb.nodesource.com/node_5.x $(lsb_release -c -s) main" &&   (curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -) &&   apt-get update &&   apt-get install -y nodejs &&   apt-get clean' returned a non-zero code: 100
```

**Comment by MJFoster** [comment]
@mjfoster83 @ian-ross ... I've received a few emails concerning this issue, but I'm "mfoster" not "mjfoster83".  I'll forward the email to mjfoster@mit.edu as well.  Good luck solving your issue! 
~MJ

**Comment by mojodna** [comment]
@ian-ross it looks like `docker build` is caching some steps, specifically the ones that run `apt-get update` (it looks like you have stale sources).

To avoid this, add `--no-cache` when building.

**Comment by ian-ross** [comment]
@mojodna Thanks for the tip.  I'll give that a try!

**Comment by ian-ross** [comment]
OK, that didn't help a lot.  Still a little bit stumped about what's going on.  There's some really weird stuff in the Docker logs on the Elastic Beanstalk instance.  Anyway, I'm away until next Wednesday, so I'll have to shelve this for the moment.  @mjfoster83: I'll investigate some more next week.  Sorry this is taking a while.  It's weird as anything.

**Comment by quincylvania** [comment]
Closing as stale.
