### ISSUE TITLE
new FieldPapers doesn't support postcode in search

### ISSUE THREAD

**Issue by danstowell** [fieldpapers/fieldpapers#249]
Searching by postcode is really common in the UK. Old fieldpapers supported it, the new one doesn't - that's a shame!

For example, search "e1 4ns" - "No results were found". It should find an area in East London.

OSM doesn't hold many UK postcodes (this is deliberate) so I presume there was some other service involved in the lookup.

**Comment by ian-ross** [comment]
The new search box is powered by MapZen Search (https://mapzen.com/projects/search/).  This uses the Pelias geocoder, which is committed to using open data, and there has been some discussion about adding support for UK and US postcodes from publicly available datasets: https://github.com/pelias/pelias/issues/254 and https://github.com/pelias/pelias/issues/111 are relevant, but I don't know when those things are going to happen.

**Comment by dianashk** [comment]
Hey all! 👋 We're excited to announce that since our last release a few days ago, we now support postalcode search!  🎉 

For example, the query for ["e1 4ns"](https://search.mapzen.com/v1/search?text=e1%204ns) now returns `E1 4NS, London, England, United Kingdom`

Let us know over at https://github.com/pelias/pelias if you run into any issues with this new functionality.

**Comment by quincylvania** [comment]
Sounds like this should have been closed 6 years ago! Field Papers search is currently broken, but that's another issue (#282)
