### ISSUE TITLE
transfer josm-fieldpapers plugin to JOSM organization

### ISSUE THREAD

**Issue by almccon** [fieldpapers/fieldpapers#275]
@don-vip makes a good point that the plugin maybe should move to the @JOSM organization. Any objections?

https://github.com/fieldpapers/josm-fieldpapers/commit/60977f2e4be1628dd4d83a2d8968c5710c28c45f#commitcomment-23370265

See also https://josm.openstreetmap.de/ticket/14801

cc @bastik @floscher @iandees @Rub21 @simon04

**Comment by floscher** [comment]
Sure, transfering it would help with updating for newer JOSM APIs and getting i18n-updates from time to time.

But I have to say, personally I'm not a big fan of the centralized way that JOSM plugins are managed in the JOSM organization (I'm aware that this partly comes from the need to integrate with the SVN repo). But I don't wanna go deep into that discussion, just wanted to note, that I struggled at times with the decision, that the Mapillary plugin moved to the JOSM organization instead of maintaining it as an independent git repo.

For abandoned projects like this (12 commits in 4 years, 99 additions and 81 deletions, only one of these commits actually adds functionality) it might be a good solution to delegate the task of updating to newer JOSM API and updating translations to the JOSM maintainers, but for other projects I'm not so sure.

In my opinion, a more sustainable (but without a question harder) approach would be to revive a developer community for the plugin. If the plugin is developed actively, the developers will notice any breaking changes and adapt the plugin.
So maybe spreading the word that there is a need for developers would already help a bit. Your issue here has probably already motivated @ovruni and me to open pull requests, which fix the issue. And at least I would also be happy to help in the future with keeping the plugin up to date, and if I find time also add features.

I also find the first hurdle to developing JOSM plugins rather high, so I tried to lower that by building with Gradle. This reduces the setup for plugins (e.g. the Mapillary plugin) to the following:
```shell
git clone ‹insert URL of git-repo here›
./gradlew build
```
That's it! This downloads, builds and tests the project, only Java and git is required to be installed. With `./gradlew runJosm`, you can even fire up a JOSM instance with only the plugin loaded, which you are currently developing.
Currently my Gradle setup is not capable of updating the translations, but I'm working on integrating that.
If you want to try it, I've set that up for the fieldpapers plugin in [my fork of it](https://github.com/floscher/josm-fieldpapers).

**Comment by don-vip** [comment]
I just proposed this as an immediate option for us to fix the plugin. This only takes 5 minutes to update the single line, build the jar and publish it. But obviously not a single developer of this plugin cares enough to spend these 5 minutes on it. If you manage to revive a developer community, that's of course better. 

I'm not a fan of plugin forks at all when they're not created to submit back a PR but take over the project. We have several past experiences of dev1 creating a plugin then abandoning it, dev2 forking it, then abandoning its own fork, dev3 doing the same, etc. etc. That's a pain for us to track who's maintaining a given plugin. Having them all centralized in JOSM organization is a lot simpler for us.

**Comment by iandees** [comment]
@don-vip why does it need to be simpler for JOSM devs? If you want to include the features in the main JOSM organization or code and maintain it, then doesn't it make more sense to take the code from the plugin and include it in the JOSM core?

**Comment by floscher** [comment]
> This only takes 5 minutes to update the single line, build the jar and publish it. But obviously not a single developer of this plugin cares enough to spend these 5 minutes on it.

I did exactly that and also @ovruni offered his help. We can't publish releases here, that's why I created a (temporary) fork, to provide a fixed version as soon as possible.

> I'm not a fan of plugin forks at all when they're not created to submit back a PR but take over the project.

Me neither! I created the fork in order to create a [pull request](https://github.com/fieldpapers/josm-fieldpapers/pull/3) and it serves as a temporary place for hosting [the released *.jar file](https://github.com/floscher/josm-fieldpapers/releases/tag/v0.4.2), because I can't publish it in the original repo and it looked as if this will probably take some time until the PR gets merged.

**Comment by iandees** [comment]
I'm happy to merge pull requests and publish new releases against [the original repository](https://github.com/iandees/josm-fieldpapers).

**Comment by don-vip** [comment]
@iandees because we're the ones spammed with bug reports from abandoned plugins! I would like to spend my time to do other things than triaging those bug reports because some external developer abandoned his/her work.

**Comment by don-vip** [comment]
@floscher : Yes I see. Thanks a lot, that's exactly what needed to be done 👍

**Comment by almccon** [comment]
The other option is that I can add any/all of you as administrators on fieldpapers fork of the repository, and we can just leave it in place. It doesn't matter to me at all. For now I'll definitely add @iandees since we're a fork from his repo anyway.

**Comment by iandees** [comment]
It think it makes sense to move the repo over to the fieldpapers org.

**Comment by ovruni** [comment]
So, where should I send some pull request in the future?

**Comment by iandees** [comment]
@ovruni https://GitHub.com/iandees/josm-fieldpapers. That will redirect to fieldpapers/josm-fieldpapers when I move it.

**Comment by iandees** [comment]
@almccon can you give me permission to create repos in fieldpapers org? That, combined with moving or deleting the fieldpapers/josm-fieldpapers repo mean I can move "my" fork in to replace the one that's in fieldpapers org now.

**Comment by floscher** [comment]
Any progress on this issue? This should be solved so that everything is in one place. Where this place is, is secondary as long as it's not all scattered over three "fork-levels".

This can only be done by someone with some admin rights on both `iandees/josm-fieldpapers` and `fieldpapers/josm-fieldpapers` as @iandees has outlined above. @almccon, can you give @iandees the needed permissions? (@iandees: If you'd need support in doing that, I could also offer my help)

@iandees: I recently played around again with the project and tried to add [the history of the `walkingpapers` project](https://github.com/floscher/josm-fieldpapers/commits/master?after=78aa3240842278ded6ff6b8a66f708a5eeaf9557+34) (before the split into `walkingpapers` and `fieldpapers`) to the git-tree in my fork. Would this be something, that we should keep? There are also some new changes, that I'd offer via PR, but I wanted to ask first about adding the `walkingpapers`-history.

**Comment by iandees** [comment]
I'm inclined to leave out `walkingpapers`' history but don't have a strong opinion.

@almccon, you added me to the fieldpapers organization but I need to be an admin on this repo so I can rename it.

**Comment by almccon** [comment]
Okay, @iandees, try now. 

I also agree that we can leave out `walkingpapers`.

**Comment by floscher** [comment]
Then ok, let's leave the history without the changes made before the `fieldpapers` plugin forked from the `walkingpapers` plugin. My opinion about that wasn't very strong either. It just came to my mind when [the `walkingpapers` plugin was discontinued and removed from the SVN repo earlier this year](https://josm.openstreetmap.de/ticket/15302).

I'll wait then until the migration is finished and then open a PR with the changes I made in my fork compared to the main repo.

**Comment by iandees** [comment]
https://github.com/fieldpapers/josm-fieldpapers

... is now the root repo.

**Comment by floscher** [comment]
Thanks, great! And even the forks and everything is carried over.

**Comment by floscher** [comment]
Just one more thing, then we can probably close this issue:
Could you also transfer the git-tags to the new repo, so these are all in one place (currently there are only `0.1`, `0.2` and `v0.2.1`).

```bash
git remote add floscher git@github.com:floscher/josm-fieldpapers.git
git remote add fieldpapers git@github.com:fieldpapers/josm-fieldpapers.git
git fetch floscher --tags
git push fieldpapers --tags
```

**Comment by iandees** [comment]
Tags pushed.

**Comment by quincylvania** [comment]
https://github.com/fieldpapers/josm-fieldpapers/issues/15#issuecomment-1494937248
