### ISSUE TITLE
Translations: not translated texts remaining

### ISSUE THREAD

**Issue by severinmenard** [fieldpapers/fieldpapers#50]
it may be normal for the moment, just for info:

the whole page:
![selection_037](https://cloud.githubusercontent.com/assets/1291055/7208775/a70f592e-e532-11e4-80ca-f1488c3bb402.png)

the whole page:
![selection_036](https://cloud.githubusercontent.com/assets/1291055/7208778/acb8a524-e532-11e4-9052-d12568cad10c.png)

not translated are anonymous + translating missing:
![selection_035](https://cloud.githubusercontent.com/assets/1291055/7208780/b0ef1844-e532-11e4-8ac5-00ca5474fa53.png)

not translated is truncate:
![selection_034](https://cloud.githubusercontent.com/assets/1291055/7208783/b75c6ba0-e532-11e4-8f69-a15e47075915.png)

**Comment by mojodna** [comment]
The "Advanced Tools" page is kind of a special case since it's effectively a wall of text.  We could split out individual paragraphs, but it might make more sense to duplicate the page and provide additional versions as `advanced.html.fr.erb` (or similar).  @severinmenard what's your opinion on this?  You're the primary translator who also maintains a GitHub presence (and can be mentioned via @fieldpapers/fr).

Authentication-related stuff is tracked in #13, since we've changed few of the strings from their default values and it's likely that translated versions exist, which we can use to limit the amount of translation work necessary.

**Comment by severinmenard** [comment]
I can translate the Advanced tools offline with QT Linguist and send a pull request. Can you please provide the link of the page?

**Comment by mojodna** [comment]
@severinmenard https://github.com/fieldpapers/fp-web/blob/master/app/views/home/advanced.fr.html.erb

Thanks!!

**Comment by mojodna** [comment]
I've tracked down some shared translations for default Rails strings as well as kaminari (the gem we're using for pagination), which should improve coverage dramatically without requiring any new strings to be translated.
